# Generated by Django 3.2.9 on 2022-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagNumber', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
